In [209]:
import numpy as np

In [210]:
text1 = """
امروز به خانه رفتم.
در مسیر خانه ناگهان گربه فریاد زد و ترسیدم.
وقتی رسیدم باران قطع شده و رنگین کمان زیبایی در آسمان ظاهر شد.
با گرفتن یک عکس این لحظه زیبا را ابدی کردم.
دست به جیب شده و کلید را برداشتم.
متاسفانه ولی کلید نبود.
"""

In [211]:
text2 = """
امروز به خانه رفتم.
در مسیر خانه ناگهان ترسیدم.
وقتی رسیدم باران قطع شده و رنگین کمان زیبایی در آسمان ظاهر شد.
سعی کردم لحظه را ابدی کنم.
نبود کلید متاسفانه ولی.
خوشبختانه همسرم در خانه بود.
"""

In [212]:
text_corpus = text1 + text2
vocabs = sorted(set(text_corpus.split()))
vocabs = [vocab.replace('.','') for vocab in vocabs]

In [213]:
word2idx = {u:i for i, u in enumerate(vocabs)}
idx2word = np.array(vocabs)

In [214]:
text1_list = []
text1_list_word = []
for sentent in text1.split('.'):
    text_as_int = np.array([word2idx[word] for word in sentent.split()])
    text1_list.append(text_as_int)
    text1_list_word.append(sentent)
text1_list = text1_list[:-1]

In [215]:
text2_list = []
for sentent in text2.split('.'):
    text_as_int = np.array([word2idx[word] for word in sentent.split()])
    text2_list.append(text_as_int)
text2_list = text2_list[:-1]

In [216]:
text1_list

[array([ 2,  7, 11, 17]),
 array([13, 31, 11, 32, 45, 27, 19, 36,  9]),
 array([37, 16,  5, 28, 24, 36, 18, 43, 21, 13,  0, 25, 23]),
 array([ 4, 46, 47, 26,  3, 29, 20, 15,  1, 41]),
 array([14,  7, 10, 24, 36, 42, 15,  6]),
 array([30, 39, 42, 34])]

In [217]:
text2_list

[array([ 2,  7, 11, 17]),
 array([13, 31, 11, 32,  9]),
 array([37, 16,  5, 28, 24, 36, 18, 43, 21, 13,  0, 25, 23]),
 array([22, 41, 29, 15,  1, 44]),
 array([34, 42, 30, 39]),
 array([12, 35, 13, 11,  8])]

In [218]:
text1_size = len(text1_list)
text2_size = len(text2_list)

In [219]:
text1_size

6

In [220]:
def IntersectionTwoLists(list1, list2): 
    return set(list1).intersection(list2)

In [221]:
sim_arr = np.zeros((text1_size, text2_size))

In [222]:
for i, sentent1 in enumerate(text1_list):
    for j, sentent2 in enumerate(text2_list):
        itersect = IntersectionTwoLists(sentent1, sentent2)
        if(len(itersect) != 0):
            sim_arr[i][j] = round(len(itersect)/len(set(sentent1)), 2)

In [223]:
sim_arr

array([[1.  , 0.25, 0.  , 0.  , 0.  , 0.25],
       [0.11, 0.56, 0.22, 0.  , 0.  , 0.22],
       [0.  , 0.08, 1.  , 0.  , 0.  , 0.08],
       [0.  , 0.  , 0.  , 0.4 , 0.  , 0.  ],
       [0.12, 0.  , 0.25, 0.12, 0.12, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  , 0.  ]])

In [224]:
most_sim = np.argmax(sim_arr, axis=0)
most_sim

array([0, 1, 2, 3, 5, 0], dtype=int64)

In [225]:
for i, sentent1 in enumerate(text1_list):
    sent_orgi_length = len(set(sentent1))
    for j, sentent2 in enumerate(text2_list):
        itersect = IntersectionTwoLists(sentent1, sentent2)
        if(len(itersect) != 0):
            sim = len(itersect)/sent_orgi_length
            print('similarity between sentent {} of text1 and sentent {} of text2 = {}% {}'.format(i+1 ,j+1 ,round(sim,2) , itersect))
        else:
            print('similarity between sentent {} of text1 and sentent {} of text2 = {}%'.format(i+1 ,j+1 ,0))

similarity between sentent 1 of text1 and sentent 1 of text2 = 1.0% {17, 2, 11, 7}
similarity between sentent 1 of text1 and sentent 2 of text2 = 0.25% {11}
similarity between sentent 1 of text1 and sentent 3 of text2 = 0%
similarity between sentent 1 of text1 and sentent 4 of text2 = 0%
similarity between sentent 1 of text1 and sentent 5 of text2 = 0%
similarity between sentent 1 of text1 and sentent 6 of text2 = 0.25% {11}
similarity between sentent 2 of text1 and sentent 1 of text2 = 0.11% {11}
similarity between sentent 2 of text1 and sentent 2 of text2 = 0.56% {32, 9, 11, 13, 31}
similarity between sentent 2 of text1 and sentent 3 of text2 = 0.22% {36, 13}
similarity between sentent 2 of text1 and sentent 4 of text2 = 0%
similarity between sentent 2 of text1 and sentent 5 of text2 = 0%
similarity between sentent 2 of text1 and sentent 6 of text2 = 0.22% {11, 13}
similarity between sentent 3 of text1 and sentent 1 of text2 = 0%
similarity between sentent 3 of text1 and sentent 2 of

 میزان شباهت متن دوم به متن اول محاسبه کردیم 
در این روش متن اول، مرجع بوده و نسبت به آن مقایسه صورت گرفته است

In [228]:
print('متن اول:' + text1)
print('متن دوم:' + text2)
print("جملات مشابه: ")
for i, x in enumerate(most_sim):
    if sim_arr[x][i] > .5 :
        print(text1_list_word[x].replace('\n','') + ' ' + str(sim_arr[x][i]))

متن اول:
امروز به خانه رفتم.
در مسیر خانه ناگهان گربه فریاد زد و ترسیدم.
وقتی رسیدم باران قطع شده و رنگین کمان زیبایی در آسمان ظاهر شد.
با گرفتن یک عکس این لحظه زیبا را ابدی کردم.
دست به جیب شده و کلید را برداشتم.
متاسفانه ولی کلید نبود.

متن دوم:
امروز به خانه رفتم.
در مسیر خانه ناگهان ترسیدم.
وقتی رسیدم باران قطع شده و رنگین کمان زیبایی در آسمان ظاهر شد.
سعی کردم لحظه را ابدی کنم.
نبود کلید متاسفانه ولی.
خوشبختانه همسرم در خانه بود.

جملات مشابه: 
امروز به خانه رفتم 1.0
در مسیر خانه ناگهان گربه فریاد زد و ترسیدم 0.56
وقتی رسیدم باران قطع شده و رنگین کمان زیبایی در آسمان ظاهر شد 1.0
متاسفانه ولی کلید نبود 1.0
